{{- if include "kubernetes-netskope-publisher.isStatefulSet" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-netskope-publisher.fullname" . }}-headless
  labels:
    {{- include "kubernetes-netskope-publisher.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "kubernetes-netskope-publisher.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: health
      port: 1234
      targetPort: 1234
{{- end }}
