{{- if and (not (include "kubernetes-netskope-publisher.isApiEnrollment" .)) (not .Values.registrationToken.existingSecret) .Values.registrationToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-netskope-publisher.fullname" . }}-token
  labels:
    {{- include "kubernetes-netskope-publisher.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.registrationToken.value | quote }}
{{- end }}
